config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[index show]
  resources :galleries, only: %i[index] do
    collection do
      get '/image', to: 'galleries#get_url'
    end
  end
  get '/top', to: 'tops#index'
  get '/about', to: 'about#index'
  get '/menu', to: 'menu#index'
  root to: 'tops#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get '/', to: 'home#index'
    resources :posts, only: %i[new create edit update destroy] do
      get :all, :published, :drafts, on: :collection
      post :upload_image, on: :collection
    end
    resources :categories, only: %i[index create show destroy]
    resources :galleries, only: %i[index create new destroy]
  end
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def thumbnail
    return self.image.variant(combine_options: { resize: "480x270", extent: "240x135", background: "white", gravity: "center"})
  end

  def custom_thumbnail(a, b, c, d)
    return self.image.variant(combine_options: { resize: "#{a}x#{b}", extent: "#{c}x#{d}", background: "white", gravity: "center"})
  end

  def post_thumbnail
    return self.image.variant(combine_options: { resize: "690x460>", extent: "690x460", background: "white", gravity: "center"})
  end

  def mini_thumbnail
    return self.image.variant(combine_options: { resize: "120x120", extent: "80x80", background: "white", gravity: "center"})
  end

  def images_thumbnail
    return self.images[0].variant(combine_options: { resize: "120x160", extent: "90x120", background: "white", gravity: "center"})
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations
  has_many :posts, through: :post_category_relations
  has_many :gallery_category_relations
  has_many :galleries, through: :gallery_category_relations
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :gallery_category_relations, dependent: :destroy
  has_many :categories, through: :gallery_category_relations
  has_many_attached :images

  validate :images_presence

  def images_presence
    if images.attached?
      images.each.each do |image|
        if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
          errors.add(:images, 'にはjpeg, jpgまたはpngファイルを添付してください')
        end
      end
    else
      errors.add(:images, 'ファイルを添付してください')
    end
  end
end

app/models/gallery_category_relation.rb
class GalleryCategoryRelation < ApplicationRecord
  belongs_to :gallery
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations

  enum published: { draft: false, published: true }

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
        errors.add(:image, 'にはjpeg, jpgまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: {maximum: 50}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  def email_required?
    false
  end
  def email_changed?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def get_url
    @images = Gallery.find(image_params[:id]).images
    @description = Gallery.find(image_params[:id]).description
    @images_url = []
    @images.each do |image|
      resize_img = image.variant(combine_options: { resize: "440x550", extent: "440x550", background: "white", gravity: "center"})
      @images_url.push(url_for(resize_img))
    end

    render json: { url: @images_url, description: @description }.to_json
  end

  private

  def image_params
    params.require(:image).permit(:id)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @slide_posts = Post.published
    @posts = Post.published.order('created_at DESC').page(params[:page]).per(8)
  end

  def show
    @post = Post.find(params[:id])
    if @post.published?
      @post
    else
      authenticate_user!
      @post
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  layout 'top'
  def index
    @galleries = Gallery.all.limit(8)
    @posts = Post.published.limit(3)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'サイト名',
      title: 'タイトル',
      reverse: true,
      charset: 'utf-8',
      description: 'description',
      keywords: 'キーワード',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'サイト名', # もしくは site_name: :site
        title: 'タイトル', # もしくは title: :title
        description: 'description', # もしくは description: :description
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: '@ツイッターのアカウント名',
      }
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/about/index.html.erb
<div class="container">
  <div class="about">
    <h2 class="page-title">About</h2>
    <div class="profile-wrapper row">
      <div class="profile-img col-md-5">
        <img src="assets/profile-image.jpg"/>
      </div>
      <div class="profile-description offset-md-2 col-md-5">
        <h3>武藤 篤弥</h3>
        <div class="profile-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
          dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu/index.html.erb
<h1 class="page-title">menu</h1>
<div class="menu-main">
  <div class="menu-box row">
    <h2 class="offset-md-2 col-md-4">base</h2>
    <table class="table table-borderless col-md-6">
      <tr>
        <th>cut</th><td>4400</td>
      </tr>
      <tr>
        <th>cut&color</th><td>8800~</td>
      </tr>
      <tr>
        <th>cut&perm</th><td>9900~</td>
      </tr>
    </table>
  </div>
  <div class="menu-box row">
    <h2 class="offset-md-2 col-md-4">option</h2>
    <table class="table table-borderless col-md-6">
      <tr>
        <th>全頭ブリーチ</th><td>+4400</td>
      </tr>
      <tr>
        <th>その他ブリーチデザイン</th><td>+4400</td>
      </tr>
      <tr>
        <th>ケアブリーチ</th><td>+2200</td>
      </tr>
      <tr>
        <th>縮毛矯正</th><td>+9900</td>
      </tr>
      <tr>
        <th>TOKIOトリートメント（ホームケア付き）</th><td>+6600</td>
      </tr>
      <tr>
        <th>トリートメント</th><td>+2200~11000</td>
      </tr>
    </table>
  </div>
  <div class="menu-box row">
    <h2 class="offset-md-2 col-md-4">coupon</h2>
    <ul class="col-md-6">
      <li>初回10%off</li>
      <li>ご友人のご紹介で10%off</li>
      <li>2回目1カ月以内のご来店の方に限り1000円off</li>
      <li>3回目1カ月以内のご来店の方に限り1500円off</li>
      <li>4回目以降ご来店の方に限り毎回10％off</li>
    </ul>
  </div>
</div>

app/views/tops/index.html.erb
<header class="header">
  <div class="header-content">
    <h1 class="site-title">MutoAtsuya</h1>
    <p class="site-title-sub">stylist</p>
    <i class="fas fa-chevron-circle-down toUnder"></i>
  </div>
</header>
<section class="gallery">
  <div class="container">
    <h2 class="heading">Gallery</h2>
    <div class="gallery-wrap">
      <ul class="gallery-slide">
        <% @galleries.each do |gallery| %>
        <li class="gallery-img">
          <%= image_tag gallery.images[0].variant(combine_options: { resize: "300x400", extent: "300x400", background: "white", gravity: "center"}) %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="more-btn">
      <%= link_to 'View All', galleries_path %>
    </div>
  </div>
</section>
<section class="top-blog">
  <div class="container">
    <h2 class="heading">New Posts</h2>
    <div class="post-wrap row">
      <% @posts.each do |post| %>
      <div class="post-img col-md-4">
        <%= link_to post_path(post) do %>
        <%= image_tag(post.custom_thumbnail(345, 230, 345, 230), class: 'img-fluid') %>
        <p>
          <%= post.title %>
        </p>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="more-btn">
      <%= link_to 'View All', posts_path %>
    </div>
  </div>
</section>
<section class="top-info" style="background-color: ">
  <div class="container">
    <h2 class="heading">Info</h2>
    <div class="info-wrap row">
      <div class="salon-img col-md-5">
        <img class="img-fluid" src='assets/produce.jpg' alt='サロンの写真' />
      </div>
      <div class="salon-info col-md-7">
        <h3>Produce 相模大野店</h3>
        <p>神奈川県相模原市南区相模大野４‐５‐１７　ロビーファイブ１Ｆ</p>
        <table class="table">
          <tr>
            <th>営業時間</th><td>10:00~19:00</td>
          </tr>
          <tr>
            <th>個人休み</th><td>木曜日</td>
          </tr>
        </table>
        <div class="more-btn">
          <%= link_to 'menu', menu_path %>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  $('.gallery-slide').slick({
    autoplay: true,
    dots: true,
    fade: false,
    slidesToShow: 3,
    centerMode: true,
    variableWidth: true,
  })
</script>