config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[index show]
  resources :galleries, only: %i[index] do
    collection do
      get '/image', to: 'galleries#get_url'
    end
  end
  get '/top', to: 'tops#index'
  get '/about', to: 'about#index'
  get '/menu', to: 'menu#index'
  root to: 'tops#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get '/', to: 'home#index'
    resources :posts, only: %i[new create edit update destroy] do
      get :all, :published, :drafts, on: :collection
      post :upload_image, on: :collection
    end
    resources :categories, only: %i[index create show destroy]
    resources :galleries, only: %i[index create new destroy]
  end
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def thumbnail
    return self.image.variant(combine_options: { resize: "480x270", extent: "240x135", background: "white", gravity: "center"})
  end

  def custom_thumbnail(a, b, c, d)
    return self.image.variant(combine_options: { resize: "#{a}x#{b}", extent: "#{c}x#{d}", background: "white", gravity: "center"})
  end

  def post_thumbnail
    return self.image.variant(combine_options: { resize: "690x460>", extent: "690x460", background: "white", gravity: "center"})
  end

  def mini_thumbnail
    return self.image.variant(combine_options: { resize: "120x120", extent: "80x80", background: "white", gravity: "center"})
  end

  def images_thumbnail
    return self.images[0].variant(combine_options: { resize: "120x160", extent: "90x120", background: "white", gravity: "center"})
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations
  has_many :posts, through: :post_category_relations
  has_many :gallery_category_relations
  has_many :galleries, through: :gallery_category_relations
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :gallery_category_relations, dependent: :destroy
  has_many :categories, through: :gallery_category_relations
  has_many_attached :images

  validate :images_presence

  def images_presence
    if images.attached?
      images.each.each do |image|
        if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
          errors.add(:images, 'にはjpeg, jpgまたはpngファイルを添付してください')
        end
      end
    else
      errors.add(:images, 'ファイルを添付してください')
    end
  end
end

app/models/gallery_category_relation.rb
class GalleryCategoryRelation < ApplicationRecord
  belongs_to :gallery
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations

  enum published: { draft: false, published: true }

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
        errors.add(:image, 'にはjpeg, jpgまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: {maximum: 50}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  def email_required?
    false
  end
  def email_changed?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  require 'aws-sdk-s3'
  before_action :authenticate_user!

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "記事を投稿しました。"
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update!(post_params)
      redirect_to post_path(@post), notice: "記事を編集しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_back(fallback_location: root_path, notice: "記事「#{@post.title}」を削除しました。")
  end

  def all
    @posts = current_user.posts.all
  end

  def published
    @posts = current_user.posts.published
  end

  def drafts
    @posts = current_user.posts.draft
  end

  def upload_image
    @file = params[:file].tempfile
    @key_name = "#{SecureRandom.hex}"  # バケットに置く際のキー名
    @s3 = Aws::S3::Resource.new(
      region: 'ap-northeast-1',  # リージョン東京
      credentials: Aws::Credentials.new(
        ENV['AWS_ACCESS_KEY_ID'],
        ENV['AWS_SECRET_ACCESS_KEY']
      )
    )
    obj = @s3.bucket(ENV['S3_BUCKET_NAME']).object(@key_name)
    obj.put(body: @file, acl: 'public-read')
    render(json: { url: obj.public_url })
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :published, :image, category_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def get_url
    @images = Gallery.find(image_params[:id]).images
    @description = Gallery.find(image_params[:id]).description
    @images_url = []
    @images.each do |image|
      resize_img = image.variant(combine_options: { resize: "440x550", extent: "440x550", background: "white", gravity: "center"})
      @images_url.push(url_for(resize_img))
    end

    render json: { url: @images_url, description: @description }.to_json
  end

  private

  def image_params
    params.require(:image).permit(:id)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @slide_posts = Post.published
    @posts = Post.published.order('created_at DESC').page(params[:page]).per(8)
  end

  def show
    @post = Post.find(params[:id])
    if @post.published?
      @post
    else
      authenticate_user!
      @post
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  layout 'top'
  def index
    @galleries = Gallery.all.limit(8)
    @posts = Post.published.limit(3)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'サイト名',
      title: 'タイトル',
      reverse: true,
      charset: 'utf-8',
      description: 'description',
      keywords: 'キーワード',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'サイト名', # もしくは site_name: :site
        title: 'タイトル', # もしくは title: :title
        description: 'description', # もしくは description: :description
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: '@ツイッターのアカウント名',
      }
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/posts/index.html.erb
<div class="background-img">
  <!-- <img src="assets/back-img.jpg" /> -->
</div>
<h1 class="page-title">Blog</h1>
<div class="posts-main">
  <% @posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <div class="card-box row border-bottom border-dark">
        <div class="card-img col-md-5">
          <% if post.image.attached? %>
            <%= image_tag(post.thumbnail, class: 'img-fluid') %>
          <% else %>
            <img src="/assets/no-image.png" class="card-img"/>
          <% end %>
        </div>
        <div class="card-description col-md-7">
          <span class="post-date"><%= post.updated_at.to_s(:datetime) %></span>
          <h3 class="post-title"><%= post.title %></h3>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="paginate">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post">
  <div class="post-sub">
    <h1 class="post-title">
      <%= @post.title %>
    </h1>
    <% if @post.user == current_user %>
    <span class="post-edit"><%= link_to '編集', edit_admin_post_path(@post) %></span>
    <% end %>
    <ul class="post-category">
      <% @post.categories.each do |category| %>
        <li class="item">
          <%= category.name %>
        </li>
      <% end %>
    </ul>
    <p class="post-date">
      <%= @post.created_at.to_s(:datetime) %>
    </p>
    <div class="post-img">
      <%= image_tag(@post.post_thumbnail) if @post.image.attached? %>
    </div>
  </div>
  <div class="post-main">
    <div class="post-text custom-head">
      <%== @post.text %>
    </div>
  </div>
  <div class="shareList">
    <%= link_to 'Twitterでシェア', "https://twitter.com/share?url=#{request.url}", class: 'shareList__link icon-twitter', title: 'Twitter', target: '_blank' %>
    <%= link_to 'Facebookでシェア', "https://www.facebook.com/sharer/sharer.php?u=#{request.url}", class: 'shareList__link icon-facebook', title: 'Facebook', target: '_blank' %>
    <%= link_to 'LINEでシェア', "http://line.me/R/msg/text/?#{request.url}", class: 'shareList__link icon-line', title: 'LINE', target: '_blank' %>
  </div>
</div>