config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[index show]
  resources :galleries, only: %i[index] do
    collection do
      get '/image', to: 'galleries#get_url'
    end
  end
  get '/top', to: 'tops#index'
  get '/about', to: 'about#index'
  get '/menu', to: 'menu#index'
  root to: 'tops#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get '/', to: 'home#index'
    resources :posts, only: %i[new create edit update destroy] do
      get :all, :published, :drafts, on: :collection
      post :upload_image, on: :collection
    end
    resources :categories, only: %i[index create show destroy]
    resources :galleries, only: %i[index create new destroy]
  end
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def thumbnail
    return self.image.variant(combine_options: { resize: "480x270", extent: "240x135", background: "white", gravity: "center"})
  end

  def custom_thumbnail(a, b, c, d)
    return self.image.variant(combine_options: { resize: "#{a}x#{b}", extent: "#{c}x#{d}", background: "white", gravity: "center"})
  end

  def post_thumbnail
    return self.image.variant(combine_options: { resize: "690x460>", extent: "690x460", background: "white", gravity: "center"})
  end

  def mini_thumbnail
    return self.image.variant(combine_options: { resize: "120x120", extent: "80x80", background: "white", gravity: "center"})
  end

  def images_thumbnail
    return self.images[0].variant(combine_options: { resize: "120x160", extent: "90x120", background: "white", gravity: "center"})
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations
  has_many :posts, through: :post_category_relations
  has_many :gallery_category_relations
  has_many :galleries, through: :gallery_category_relations
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :gallery_category_relations, dependent: :destroy
  has_many :categories, through: :gallery_category_relations
  has_many_attached :images

  validate :images_presence

  def images_presence
    if images.attached?
      images.each.each do |image|
        if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
          errors.add(:images, 'にはjpeg, jpgまたはpngファイルを添付してください')
        end
      end
    else
      errors.add(:images, 'ファイルを添付してください')
    end
  end
end

app/models/gallery_category_relation.rb
class GalleryCategoryRelation < ApplicationRecord
  belongs_to :gallery
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations

  enum published: { draft: false, published: true }

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
        errors.add(:image, 'にはjpeg, jpgまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: {maximum: 50}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  def email_required?
    false
  end
  def email_changed?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def get_url
    @images = Gallery.find(image_params[:id]).images
    @description = Gallery.find(image_params[:id]).description
    @images_url = []
    @images.each do |image|
      resize_img = image.variant(combine_options: { resize: "440x550", extent: "440x550", background: "white", gravity: "center"})
      @images_url.push(url_for(resize_img))
    end

    render json: { url: @images_url, description: @description }.to_json
  end

  private

  def image_params
    params.require(:image).permit(:id)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @slide_posts = Post.published
    @posts = Post.published.order('created_at DESC').page(params[:page]).per(8)
  end

  def show
    @post = Post.find(params[:id])
    if @post.published?
      @post
    else
      authenticate_user!
      @post
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  layout 'top'
  def index
    @galleries = Gallery.all.limit(8)
    @posts = Post.published.limit(3)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'サイト名',
      title: 'タイトル',
      reverse: true,
      charset: 'utf-8',
      description: 'description',
      keywords: 'キーワード',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'サイト名', # もしくは site_name: :site
        title: 'タイトル', # もしくは title: :title
        description: 'description', # もしくは description: :description
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: '@ツイッターのアカウント名',
      }
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light  fixed-top top-nav" id="mainNav">
  <a class="navbar-brand" href="/">Muto Atsuya</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'About', about_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog', posts_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gallery', galleries_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Menu', menu_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a href="<%= t('url.hotpepper') %>" class="nav-link">Reserve</a>
      </li>
    </ul>
  </div>
</nav>
<header class="header">
  <div class="header-content">
    <h1 class="site-title">MutoAtsuya</h1>
    <p class="site-title-sub">stylist</p>
    <i class="fas fa-chevron-circle-down toUnder"></i>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm fixed-top" id="mainNav">
  <a class="navbar-brand" href="/">Muto Atsuya</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    Menu
    <i class="fas fa-bars"></i>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'About', about_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog', posts_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gallery', galleries_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Menu', menu_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a href="<%= t('url.hotpepper') %>" class="nav-link">Reserve</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MutoAtsuya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin_side' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MutoAtsuya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script|Roboto&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MutoAtsuya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'top', media: 'all' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script|Roboto&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'top', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_admin_side.html.erb

<div class="header"></div>
<input type="checkbox" class="input-check openSidebarMenu" id="openSidebarMenu">
<label for="openSidebarMenu" class="sidebarIconToggle">
  <div class="spinner diagonal part-1"></div>
  <div class="spinner horizontal"></div>
  <div class="spinner diagonal part-2"></div>
</label>
<div id="sidebarMenu">
  <ul class="sidebarMenuInner">
    <li><i class="fas fa-home"></i><%= link_to 'Home', root_path %></li>
    <li><i class="fas fa-chart-bar"></i><%= link_to 'Dashboard', admin_path %></li>
    <li><i class="fas fa-pen-square"></i><%= link_to 'New Post', new_admin_post_path %></li>
    <li><i class="fas fa-file-code"></i>
      <%= link_to 'All Posts', all_admin_posts_path %>
      <ul>
        <li>-<%= link_to 'Published', published_admin_posts_path, class: 'li-child' %></li>
        <li>-<%= link_to 'Drafts', drafts_admin_posts_path, class: 'li-child' %></li>
      </ul>
    </li>
    <li><i class="fas fa-camera"></i><%= link_to 'All Galleries', admin_galleries_path %></li>
    <li><i class="fas fa-camera"></i><%= link_to 'New Gallery', new_admin_gallery_path %></li>
    <li><i class="fas fa-tags"></i><%= link_to 'Category', admin_categories_path %></li>
    <li><i class="fas fa-sign-out-alt"></i><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/shared/_footer.html.erb
<footer class="footer mt-3">
  <div class="footer-wrap">
    <ul class="list-inline text-center">
      <li class="list-inline-item">
        <a href="<%= t('url.twitter') %>">
          <span class="fa-stack fa-lg">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
          </span>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="<%= t('url.instagram') %>">
          <span class="fa-stack fa-lg">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
          </span>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="<%= t('url.youtube') %>">
          <span class="fa-stack fa-lg">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
          </span>
        </a>
      </li>
    </ul>
    <p class="copyright text-muted text-center mb-0">Copyright &copy; Muto Atsuya 2019</p>
  </div>
</div>

app/views/shared/_gallery_list.html.erb
<div class="gallery">
  <div class="gallery-wrapper row">
    <% @galleries.each do |gallery| %>
    <div class="modal-open-box" data-id="<%= gallery.id %>">
      <%= image_tag(gallery.images_thumbnail, class: 'img-thumbnail') %>
    </div>
    <% end %>
  </div>
  <div class="modal js-modal">
    <div class="modal_bg modal-close"></div>
    <div class="modal_content">
      <div class="modal-img-wrap">
      </div>
      <p class="modal-description">
      </p>
      <a class="modal-close" href="">閉じる</a>
    </div>
  </div>
</div>

app/views/shared/button/_instagram.html.erb
<a href="https://instagram.com/atsuya.0724" class="btn-social-long-insta sns">
  <i class="fab fa-instagram"></i> <span>Instagram</span>
</a>

app/views/shared/button/_reserve.html.erb
<a href="#" class="btn-cut-reserve sns">
  <i class="fas fa-cut"></i> <span>Reserve</span>
</a>

app/views/shared/button/_twitter.html.erb
<a href="https://twitter.com/atsurad_724" class="btn-social-long-twitter sns">
  <i class="fab fa-twitter"></i> <span>Twitter</span>
</a>

app/views/shared/button/_youtube.html.erb
<a href="#" class="btn-social-long-youtube sns">
  <i class="fab fa-youtube"></i> <span>Youtube</span>
</a>